### ISSUE TITLE
npm not up to date with getReferents

### ISSUE THREAD

**Issue by unsalted** [alexbooker/node-genius#4]
Heads up ^^^^

**Comment by bookercodes** [comment]
I'll get on this before I go to bed. Thanks.

**Comment by bookercodes** [comment]
Should be updated. Can you please confirm?

**Comment by unsalted** [comment]
Appears to have it now.  Out of curiosity, is there a method of actually pulling lyrics through their api or do they make that intentionally impossible so I have to resort to tradition scraping?

**Comment by bookercodes** [comment]
@unsalted [It's not possible.](http://genius.com/6891554)
